### ISSUE TITLE
Wood cutter crafting a monster sprite,

### ISSUE THREAD

**Issue by Xillith** [talonos2/FinalWinterBugs#153]
Monsters sprite needed made from wood, and a carved sprite needed made from wood

**Comment by Xillith** [comment]
placed in the woodcutter intro scene (day 17 I think), preferably on the map from then on.

**Comment by Xillith** [comment]
In the game now. But we should add a sound effect for when he cuts it in half

**Comment by Ipecacuanha** [comment]
Cut carving added to days after Woodcutter leaves

**Comment by Ipecacuanha** [comment]
sound FX added
