### ISSUE TITLE
scarcrow needs to replace hiro in starting cutscene, map 24

### ISSUE THREAD

**Issue by Xillith** [talonos2/FinalWinterBugs#157]
There should probably be scarecrows in town before each day

**Comment by Xillith** [comment]
Also needs to replace the hiro in cs number 5

**Comment by Xillith** [comment]
Maybe add them to cutscene 6

**Comment by Xillith** [comment]
should be added to town map 20-24 (single attack dummy)

**Comment by Ipecacuanha** [comment]
added to cutscene 24

**Comment by Ipecacuanha** [comment]
Scarecrows added to cs 5, 6, and 24. scarecrows are intentionally absent in 19-23 one returns for 24 and 25 before going away again.  issue on cs 5 remains open until I learn how to animate it.
