### ISSUE TITLE
In the opening cutscene, the seer's furtive rightward glance should be re-timed so as to not indicate an earthquake.

### ISSUE THREAD

**Issue by talonos2** [talonos2/FinalWinterBugs#199]
Right now, the seer glances to the right just before mentioning that there are earthquakes. Given that this is the first time you ever see a character change facing, it makes it appear as though the seer's movement is related to the earthquake, leading me (and Emily) to believe an earthquake *just* happened.

**Comment by Ipecacuanha** [comment]
no longer necessary with new intro
