### ISSUE TITLE
Make it so our logo pops up faster

### ISSUE THREAD

**Issue by Xillith** [talonos2/FinalWinterBugs#279]
*Right after unity logo load have spaceheater games logo
*then fade to black and start snow
*Then once snow hits bottom of screen, add 'press enter to start'
(If there is any way to load this first, then everything else)

**Comment by talonos2** [comment]
Need art for this. Pulling in @Drawmadillo

**Comment by Xillith** [comment]
Logo scene now in. We will wait for next beta to see how it feels as the snowfall on a black screen idea I don't think will work.

**Comment by talonos2** [comment]
We've got snow in the main menu now. I don't know why I thought we needed this; I thought I saw an issue for it, but this was the closest I could find. :/

**Comment by Xillith** [comment]
Not enough time. Calling issue and removing. (Players can wait the extra 3-5 seconds on the unity screen this would save)
