### ISSUE TITLE
Town hall should have several shadows from the shadow layer baked into the scene.

### ISSUE THREAD

**Issue by talonos2** [talonos2/FinalWinterBugs#287]
In the town, no characters carry light sources, so anything on the shadow layer will affect the characters as well. In the town hall (and pretty much only the town hall) the shadow layer makes some ugly stuff happen. In particular, the shadows on the desk and the shadows on the bookshelves need to be baked into the map itself and removed from the shadow layer.

**Comment by Xillith** [comment]
Current list of graphical issues in 'bugs, at Nov 28th. Most are programming related

**Comment by Xillith** [comment]
all the ones to be fixed by code are fixed. What is left is the ones mentioend on the town art channel
