### ISSUE TITLE
The snow on the roof of the building next to the inn should not cover the pipes of the building in front of it.

### ISSUE THREAD

**Issue by talonos2** [talonos2/FinalWinterBugs#288]
What I see:

![image](https://user-images.githubusercontent.com/3359830/92420108-c4c11800-f12e-11ea-90cb-fe3e66a43150.png)

What I expect to see:

![image](https://user-images.githubusercontent.com/3359830/92420139-f3d78980-f12e-11ea-908b-519be66dd53f.png)

Check other buildings in town for similar issues.

**Comment by Xillith** [comment]
Partly done. Snow on the left done. 2 on right still need art
