### ISSUE TITLE
Urgent: Zombies appear too early

### ISSUE THREAD

**Issue by Ipecacuanha** [talonos2/FinalWinterBugs#353]
Zombies appear as soon as the character is dead, not when the player has the element to avoid them.

Urgent: This functionally soft-locks the beta after run 5 because the player is very underpowered to fight zombie Sara.

**Comment by Xillith** [comment]
via testing bug still exists.

**Comment by Xillith** [comment]
fixed on my computer now, so should be robust enough to push out
