### ISSUE TITLE
need better timing and clarity for resting tutorial

### ISSUE THREAD

**Issue by Ipecacuanha** [talonos2/FinalWinterBugs#366]
players seem to forget about it quickly. Or maybe the initial tutorial should force them to use it?

**Comment by Xillith** [comment]
I think this is now solved by the following: 

1: When at low health there is an alert on the bottom left, and the key to press to heal is right there next to the alert. This will prevent a person from forgetting to use it, and forgetting which key to use.

**Comment by Xillith** [comment]
Low health tracker on bottom right with button to press next to it solves this issue
