### ISSUE TITLE
Profile Bust spot and size needs to be checked for each dungeon run, and made to be similar to Hiro's

### ISSUE THREAD

**Issue by Xillith** [talonos2/FinalWinterBugs#43]
Profile Bust spot and size needs to be checked for each dungeon run, and made to be similar to Hiro's

Note that it is probably ok if everyone other than hiro is more locked in their box, as a way of showing off how sad everyone else is.

**Comment by Ipecacuanha** [comment]
Looking through the list I think everyone could use a small nudge to the left.
I could probably implement the changes, I'd just need to be pointed in the right direction.

(19)Sir Meyster seems quite small, but is also quite broad.  I think we can size him up though.
(12)Stranger is just downright tiny
(11)Pendleton is SUPER tiny 
(9) Devon is a little smaller than average, but also somewhat broad

**Comment by Xillith** [comment]
busts fixed through out game. Eyes are now all in roughly the same locations.
