### ISSUE TITLE
These few squares in the town should be pathable:

### ISSUE THREAD

**Issue by talonos2** [talonos2/FinalWinterBugs#517]
![image](https://user-images.githubusercontent.com/3359830/106216058-84bb0a00-618f-11eb-9a51-1a2f63797c3d.png)

**Comment by Ipecacuanha** [comment]
It is done. Now the players may explore the mysteries of the spot slightly right of the hedge.

**Comment by talonos2** [comment]
Thanks, bob. I know there's nothing there, but when a tester tried to step
on it and it didn't work, he said "Huh. I guess I can only walk on roads."
