### ISSUE TITLE
Dialogues seem to be auto clicking on themselves, inconsistent, no apparent pattern.

### ISSUE THREAD

**Issue by Ipecacuanha** [talonos2/FinalWinterBugs#522]

**Comment by Xillith** [comment]
So far unreproduceable on my or brennans computer. 

Is this happening during dialogue or during ending cutscenes or what?

**Comment by Xillith** [comment]
*Accidentally closed

**Comment by Ipecacuanha** [comment]
Just during dialogue. So far has only happened on my wife's computer. We should probably put this on low priority for now.
