### ISSUE TITLE
Glow should be less on some maps, either by modifying ShadowLoader to accept a glow amount or by manually adjusting the glowmap translucency.

### ISSUE THREAD

**Issue by Xillith** [talonos2/FinalWinterBugs#64]

**Comment by Xillith** [comment]
Alternatively we could just go into the glow image and fix it there on the maps affected.  Not a high priority

**Comment by Xillith** [comment]
May be easier to manually edit the glow map on maps where it's needed to make the glow map more 'transparent', aka less glowy

**Comment by talonos2** [comment]
You now have a variable called "_GlowAmount", a float from 0 to 1. 1 is full glow. Anything less is a multiplier on the glow.
